repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: local
  hooks:
  - id: pytest
    name: Run unit tests
    entry: pytest
    args: [your_assistant/tests]
    language: system
    pass_filenames: false

  - id: coverage
    name: Test coverage
    entry: coverage run -m pytest your_assistant/tests
    language: system
    pass_filenames: false
    requires: [pytest]

  - id: coverage_report
    name: Test coverage threshold 65 check
    entry: coverage report --fail-under=65
    language: system
    pass_filenames: false
    requires: [coverage]

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3.9

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.1.1
  hooks:
  - id: mypy
