name: Run tests

on:
  push:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_draft:
    runs-on: ubuntu-latest
    outputs:
      is_draft: ${{ steps.check_pr.outputs.is_draft }}
    steps:
      - name: Check if PR is draft
        id: check_pr
        run: |
          is_draft=$(curl --header "Authorization: Bearer ${{ secrets.GH_API_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq '.draft')
          echo "is_draft=$is_draft" >> $GITHUB_ENV
          echo "::set-output name=is_draft::$is_draft"
  test:
    needs: check_draft
    if: ${{ needs.check_draft.outputs.is_draft == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          echo "Current directory $PWD"; curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          poetry install ; pip install langchain; pip install -e .

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest your_assistant/tests

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy==1.1.1 isort black

      - name: Run black
        run: |
          black --check .

      - name: Run Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run mypy
        run: |
          mypy .

      - name: Run isort
        run: |
          isort --check --diff .
